// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmiZQFQPV6A0v_bzoS0OJrbWN_6S3B3Qk',
    appId: '1:927525905040:web:89a9c223cfe31a9370ee15',
    messagingSenderId: '927525905040',
    projectId: 'extrafood-f6deb',
    authDomain: 'extrafood-f6deb.firebaseapp.com',
    storageBucket: 'extrafood-f6deb.firebasestorage.app',
    measurementId: 'G-VE24028MY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDvtTCJP-EhTEGYR86CFlDF_2_J8dW4yo',
    appId: '1:927525905040:android:30fe22be391d382970ee15',
    messagingSenderId: '927525905040',
    projectId: 'extrafood-f6deb',
    storageBucket: 'extrafood-f6deb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmiZQFQPV6A0v_bzoS0OJrbWN_6S3B3Qk',
    appId: '1:927525905040:web:4792ddb0eaf7e0a270ee15',
    messagingSenderId: '927525905040',
    projectId: 'extrafood-f6deb',
    authDomain: 'extrafood-f6deb.firebaseapp.com',
    storageBucket: 'extrafood-f6deb.firebasestorage.app',
    measurementId: 'G-53SWCWMS2F',
  );
}
